apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Workshop PHP
  name: workshop-php
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and run PHP 7.2 applications.
      iconClass: icon-php
      openshift.io/display-name: PHP 7.2
      openshift.io/provider-display-name: NPO Hosting
      sampleRepo: https://github.com/sclorg/cakephp-ex.git
      supports: php:7.2,php
      tags: builder,php
      version: "7.2"
    from:
      kind: DockerImage
      name: tsterk/php:72-centos
    generation: 2
    importPolicy: {}
    name: "7.2"
    referencePolicy:
      type: Local

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: Workshop JBoss
  name: jboss-eap70-openshift
spec:
  lookupPolicy:
    local: False
  tags:
  - annotations:
      openshift.io/display-name: JBoss
      iconClass: icon-jboss
      version: "1.6"
    from:
      kind: DockerImage
      name: tsterk/eap70-openshift:1.6
    generation: 2
    importPolicy: {}
    name: "1.6"
    referencePolicy:
      type: Local
